### ISSUE TITLE
rga 是否已经对接到 gstreamer

### ISSUE THREAD

**Issue by qgyhd1234** [airockchip/librga#14]
目前使用 rk3568 开发摄像头相关应用，使用opencv和gstreamer，目前发现 videoconvert 使用cpu进行 YUY2 到 BGR 的转换，很浪费cpu。
我在 rk3288 上使用 gstreamer 时有提示加载 librga.so，在3568上并没有看到，是还没有适配吗？

**Comment by Cerf-Yu** [comment]
gstreamer方面的问题建议提一个redmine咨询
