### ISSUE TITLE
rk3588 做画中画，和淡入淡出时 视频闪烁问题

### ISSUE THREAD

**Issue by yukuilong** [airockchip/librga#16]
运行时没有报任何错误，如果视频没有重叠不会出现闪烁问题，只要有视频叠加了就会出现叠加处视频闪烁问题

**Comment by Cerf-Yu** [comment]
视频叠加是否是两个YUV格式进行叠加呢？如果是的话librga不支持两张YUV叠加的。

**Comment by yukuilong** [comment]
用yuv或者转成rgba8888都试过 ，一样的现象，在视频重叠处而偶闪烁

**Comment by Cerf-Yu** [comment]
可以尝试RGBA8888和RGBA8888之间进行叠加看看是否还会有闪烁的问题，如果依旧有的话建议将问题提到redmine平台上。
