### ISSUE TITLE
RGA_BLIT问题

### ISSUE THREAD

**Issue by Jalen321** [airockchip/librga#17]
我在输入MP4视频尺寸为1280x720时，遇到了RGA_BLIT fail :  Invail argument

![8223e374c23e9cf8226cb07dc44885c](https://user-images.githubusercontent.com/85224207/206662889-bfa0f9d4-5717-49ed-8c90-0f7d9bd8b878.jpg)

可我输入尺寸为960x540的avi视频时并没有问题。
请问这是为什么呢？我应该如何解决，谢谢。

**Comment by kunknu** [comment]
解决了吗，请问一下，我也遇到该问题
