### ISSUE TITLE
rgablit问题

### ISSUE THREAD

**Issue by Jalen321** [airockchip/librga#18]
我输入1280x720的mp4视频时出现这个错误

![图片1](https://user-images.githubusercontent.com/85224207/206665365-ead5f065-3f61-427c-849d-8969504cb8af.png)

我发现imresize的返回值是
![image](https://user-images.githubusercontent.com/85224207/206665780-0fbe85eb-f5e2-4df2-b4da-1a05ccd5b082.png)

可我输入尺寸为960x540的avi视频时并没有问题。

请问这是为什么呢？我应该如何解决，谢谢。

**Comment by Jalen321** [comment]
![image](https://user-images.githubusercontent.com/85224207/206666240-bf6f9be6-aa78-44a0-8445-4f2db75d5e81.png)

![image](https://user-images.githubusercontent.com/85224207/206666307-c7b64ed7-5570-40ad-89b2-168325819220.png)

这是我的rga驱动版本

**Comment by Cerf-Yu** [comment]
可以通过dmesg查看对应场下的驱动日志，修改分辨率时是否有修改对应buffer的size？
