### ISSUE TITLE
librga版本问题

### ISSUE THREAD

**Issue by Lyz-2022** [airockchip/librga#19]
您好，是否有2022年9月15日发布的librga版本 V2.2.   RGA格式转换时需要支持YUYV422格式输入， 1.9.0版本的lib库输入不支持此格式，还望作者可以提供一下新的rga库，十分感谢。

**Comment by Cerf-Yu** [comment]
没有发布过V2.2版本的librga，当前的1.9.0是最新版本的librga库。
另外YUYV422格式支持与否是和芯片相关的，可以对照docs下的文档中确认使用的芯片是否支持YUYV422格式输入
