### ISSUE TITLE
当rga在工作的时候，用kill -9 命令把程序杀死，会导致系统死掉

### ISSUE THREAD

**Issue by kunknu** [airockchip/librga#20]
rga在工作时不正常退出会导致系统出问题吗？

**Comment by Cerf-Yu** [comment]
RGA驱动（RGA MultiCore Device Driver）在1.2.22版本后是有针对异常的进程退出进行处理，保证kernel不会崩溃的。

**Comment by kunknu** [comment]
> RGA驱动（RGA MultiCore Device Driver）在1.2.22版本后是有针对异常的进程退出进行处理，保证kernel不会崩溃的。

请问一下，我看了文档里驱动更新源码，是需要配合其他模块比如内核？才能编译烧录，使用吗？rockchip上没有找到详细点的教程。还是这个是比较通用的流程。
