### ISSUE TITLE
drm  内存拷贝出来到普通buffer中

### ISSUE THREAD

**Issue by lawaarch** [airockchip/librga#21]
我遇见的问题是硬解码之后的drm内存。想拷贝到CPU内存，发现耗时严重，故想用rga,不知可否

**Comment by Cerf-Yu** [comment]
RGA支持不同的内存类型之间拷贝的，如你这里提到的drm-buf fd到虚拟地址之间的拷贝。

**Comment by lawaarch** [comment]
> RGA支持不同的内存类型之间拷贝的，如你这里提到的drm-buf fd到虚拟地址之间的拷贝。
示例代码中用的是虚拟buffer 拷贝到虚拟buffer 我去试试吧

**Comment by lawaarch** [comment]
我看MPP开发文档，MppBuffer 主要用于描述供硬件使用的内存块，重要参数：ptr 表示内存块的起始虚拟地址。size 表示内存块的大小。fd 表示内存块的用户态空间文件句柄。
又看RGA示例做法和开发手册：IM_API rga_buffer_handle_t importbuffer_fd(int fd, int size);
IM_API rga_buffer_handle_t importbuffer_virtualaddr(void *va, int size);
我调用之后程序总是报src has not fd and address for render，麻烦大佬解答一下。感谢

**Comment by howieOfive** [comment]
> 
我也遇到这个问题，一起看看。

**Comment by Cerf-Yu** [comment]
这个和issue #23 是一个问题吧，如日志中所示的是src通道的内存相关参数是无效的。
