### ISSUE TITLE
undefined reference to `log@GLIBC_2.29

### ISSUE THREAD

**Issue by lawaarch** [airockchip/librga#22]
使用RGA库，编译程序报错  我干脆换了个操作系统，谁知道还报同样的错误，各路大佬劳烦解答一下。不胜感激。

**Comment by xiangxiangjiang** [comment]
下载源码编译

**Comment by 15151822725** [comment]
> 下载源码编译

怎么下载源码编译呢

**Comment by lawaarch** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你把项目 下载之后有编译脚本
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/8/2023 09:45
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [airockchip/librga] undefined reference to ***@***.***_2.29 (Issue #22)
        
      
    
  
  

下载源码编译

怎么下载源码编译呢

**Comment by xiangxiangjiang** [comment]
readme下有连接



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 8, 2023 09:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airockchip/librga] undefined reference to ***@***.***_2.29 (Issue#22)




  
下载源码编译
  
怎么下载源码编译呢

**Comment by lawaarch** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    大佬能帮我解决一下，MPP解码器数据通过RGA拷贝到虚拟内存的问题不
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/8/2023 10:23
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [airockchip/librga] undefined reference to ***@***.***_2.29 (Issue #22)
        
      
    
  
  
readme下有连接







---Original---

From: ***@***.***&gt;

Date: Wed, Mar 8, 2023 09:45 AM

To: ***@***.***&gt;;

Cc: ***@***.******@***.***&gt;;

Subject: Re: [airockchip/librga] undefined reference to ***@***.***_2.29 (Issue#22)









  

下载源码编译

  

怎么下载源码编译呢
