### ISSUE TITLE
improcess坐标为(0,0)时合成背景卡死

### ISSUE THREAD

**Issue by sisid1234** [airockchip/librga#24]
improcess(a,b,c,a_rect,b_rect,c_rect,-1,NULL,NULL,IM_SYNC | IM_ALPHA_BLEND_DST_OVER);
b_rect.x 或 b_rect.y 为0时，背景就会卡死不动，前景能动，这是什么原因？

**Comment by sisid1234** [comment]
顺便问个其它问题，RK_FORMAT_YCbCr_400 这个是灰度图吧？

**Comment by sisid1234** [comment]
我用imresize，想把RK_FORMAT_YCbCr_400@480*270转成RK_FORMAT_YCbCr_400@1920*1080，提示我： Fatal error: Failed to call RockChipRga interface, query log to find the cause of failure,截取日志如下：
03-01 17:29:40.930   438   606 E librga  :  RgaBlit(1466) RGA_BLIT fail: Invalid argument
03-01 17:29:40.930   438   606 E rockchiprga: fd-vir-phy-hnd-format[0, 0x0, 0x0, 0, 0]
03-01 17:29:40.930   438   606 E rockchiprga: rect[0, 0, 480, 270, 480, 270, 5376, 0]
03-01 17:29:40.930   438   606 E rockchiprga: f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 0]
03-01 17:29:40.930   438   606 E rockchiprga: fd-vir-phy-hnd-format[0, 0x0, 0x0, 0, 0]
03-01 17:29:40.930   438   606 E rockchiprga: rect[0, 0, 1920, 1080, 1920, 1080, 5376, 0]
03-01 17:29:40.930   438   606 E rockchiprga: f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 0]
03-01 17:29:40.930   438   606 E rockchiprga: This output the user patamaters when rga call blit fail
03-01 17:29:40.930   438   606 E librga  : srect[x,y,w,h] = [0, 0, 0, 0] src[w,h,ws,hs] = [480, 270, 480, 270]
03-01 17:29:40.930   438   606 E librga  : drect[x,y,w,h] = [0, 0, 0, 0] dst[w,h,ws,hs] = [1920, 1080, 1920, 1080]
03-01 17:29:40.930   438   606 E librga  : usage[0x80000]
03-01 17:29:40.930   438   606 D OSDMCAMSsn: dequeueV4l2FrameLocked(5463): dl_gray to mpat_gray: Fatal error: Failed to call RockChipRga interface, query log to find the cause of failure.
03-01 17:29:40.930   438   606 W mali_gralloc: Could not find component description for FourCC value 0

**Comment by Cerf-Yu** [comment]
1. “Invalid argument”的问题可以参考FAQ文档中的调试日志部分，开启驱动的运行日志后抓取详细的信息，目前来看应为配置的参数无法匹配到合适的核心导致，可能和Y400格式只有RGA2核心支持有关，可以尝试参考allocator_demo中的dma_heap_dma32的内存申请方式申请内存看看。
2. 关于卡住的问题，具体是怎么个卡住这个没有描述的很清楚。可以确认一下文档中 图像合成章节确认参数是否是支持的。
