### ISSUE TITLE
RK3399是否支持imresize   interpolation设置为其他模式

### ISSUE THREAD

**Issue by OrenHg** [airockchip/librga#26]
我们项目里需要Down scale图片，项目里感觉down scale的效果不太好，锯齿太多，想要使用其他的interpolation
文档里说，RK3399所使用的RGA2硬件不支持设置interpolation模式
想问一下这个是硬件限制了就没有其他的interpolation模式吗？

还是说有通过修改软件可以达到支持其他interpolation模式的方法

**Comment by Cerf-Yu** [comment]
如文档中所示，RK3399搭载的RGA2并不支持配置interpolation，硬件上并不支持切换down scale的算法。
另外，从缩放算法的角度来看，RGA2选用的缩小算法相对来说已经是比较平滑的了，如果是opencv的bi-linear的话应该锯齿感是更重的。
