### ISSUE TITLE
librga支持透视变换吗

### ISSUE THREAD

**Issue by wulalawulala** [airockchip/librga#28]
OpenCV里面的warpPerspective

**Comment by Cerf-Yu** [comment]
这个RGA不支持的

**Comment by wulalawulala** [comment]
有计划支持吗，还是说推荐转成opencv在进行透视变换

**Comment by Cerf-Yu** [comment]
这个是当前的硬件没有支持，目前暂无这方面的计划，这部分可能还是用opencv或者调用gpu来实现。
