### ISSUE TITLE
sample for imosd

### ISSUE THREAD

**Issue by AllenDun** [airockchip/librga#29]
any sample for imsod

**Comment by AllenDun** [comment]
librga fail to get driver version!, but with 
dmesg |grep rga
it shows:
[    9.526417] rga2: Driver loaded successfully ver:3.2.18218
[    9.536528] rga2: Module initialized.
[607541.204290] rga2: unknown ioctl cmd!

**Comment by Cerf-Yu** [comment]
1. imosd仅rv1106支持。
2. 你当前使用的librga和rga驱动版本是不匹配的，详细可以看看api说明文档以及faq中关于版本说明部分。

**Comment by duiniuluantanqin** [comment]
> 1. imosd仅rv1106支持。
> 2. 你当前使用的librga和rga驱动版本是不匹配的，详细可以看看api说明文档以及faq中关于版本说明部分。

rk3588 是否支持imosd？
