### ISSUE TITLE
提示“src has not fd and address for render”问题

### ISSUE THREAD

**Issue by tangjinhan** [airockchip/librga#30]
我用rga的imcvtcolor api将yuv图像转为rgb图像，返回值显示成功，但过程中会有提示“src has not fd and address for render”，而且转换后的图像都是黑色的

**Comment by Cerf-Yu** [comment]
检查你的参数配置以及头文件版本是否和librga版本匹配，librga是否和rga驱动匹配

**Comment by RockLing-18** [comment]
> 检查你的参数配置以及头文件版本是否和librga版本匹配，librga是否和rga驱动匹配

librga和rga驱动不匹配的话，该如何解决？rga驱动能升级吗？

**Comment by Cerf-Yu** [comment]
驱动的升级文档中有介绍。
