### ISSUE TITLE
librga缩放接口imresize失败

### ISSUE THREAD

**Issue by NCU-xiaoxiaobai** [airockchip/librga#31]
rk3588板子, 我在调用imresize将720P NV12数据宽高均缩放到原来的一半 时返回失败,dmesg查看日志提示如下:
![image](https://user-images.githubusercontent.com/51814939/233939774-17a9fb36-e8d5-4e68-bdc5-f56901fb5db8.png)
另外, 720PNV12调用该接口缩放到720PNV12不会报错

**Comment by Cerf-Yu** [comment]
看起来是硬件超时了，检查一下输入输出的内存大小是否满足图像参数配置的要求。
