### ISSUE TITLE
undefined symbol: _Z8imresize12rga_buffer_tS_ddiiPi

### ISSUE THREAD

**Issue by LostmanMing** [airockchip/librga#34]
运行rknpu2/example/rknn_yolov5_demo 正常
但需要非640x640输入，需要rga缩放图片时报错,报错内容忘了，大概是api版本1.3.0过低，被废弃了。
后面编译在此仓库网盘链接的librga 1.9.1版本源码，并放在项目代码中。
运行报错：
/tmp/tmp.sTUryyl9sT/cmake-build-debug-rk3568/rknn_yolov5_demo
/tmp/tmp.sTUryyl9sT/cmake-build-debug-rk3568/rknn_yolov5_demo: symbol lookup error: /tmp/tmp.sTUryyl9sT/cmake-build-debug-rk3568/rknn_yolov5_demo: undefined symbol: _Z8imresize12rga_buffer_tS_ddiiPi

Process finished with exit code 127

请问是什么原因

**Comment by yanrihong** [comment]
请问以及解决了吗

**Comment by cena001plus** [comment]
3588上运行正常，编译的工程移植到3566上遇到同样的问题。

**Comment by kewang-seu** [comment]
> 3588上运行正常，编译的工程移植到3566上遇到同样的问题。

请问解决了吗？
