### ISSUE TITLE
rga_mm: rga_mm_map_virt_addr, cannot get current mm!

### ISSUE THREAD

**Issue by 411-3** [airockchip/librga#37]
你好！
板端运行resize缩放任务时，概率性的出现如下打印：
[   62.010470] rga_mm: rga_mm_map_virt_addr, cannot get current mm!
[   62.010498] rga_mm: rga_mm_map_buffer iommu_map virtual address error!
[   62.010504] rga_mm: job buffer map failed!
[   62.010510] rga_mm: src channel map job buffer failed!
[   62.010513] rga_job: rga_job_run: failed to map buffer
[   62.010524] rga_job: some error on rga_job_run before hw start, rga_job_next(340)

查看了QA和已有issue，未找到类似的解决说明。上述信息，也看不到是我哪里配置不对吗？

**Comment by Cerf-Yu** [comment]
更新multi-rga驱动到1.2.25版本以上。
