### ISSUE TITLE
解码后播放出现绿边

### ISSUE THREAD

**Issue by misakaj** [airockchip/librga#38]
大佬你好！我用mpp解码后，存h264的图片顶上有绿边，h265右侧有绿块（如图），请问这是什么问题？
![qimage13](https://github.com/airockchip/librga/assets/110439911/83cb9146-65d4-4606-a8b1-1cb7c49a1327)
![qimage6](https://github.com/airockchip/librga/assets/110439911/f7b5920a-8a45-4c12-b98f-7c39b8804641)

**Comment by Cerf-Yu** [comment]
1. 绿边的问题解码出来的数据是不是就是带绿边的？
2. 关于RGA的报错，你的imcheck和imcvtcolor都没有校验返回值，首先应先确认imcheck校验是否通过，如果有报错需要通过imStrError打印报错，之后依旧存在RGA_BLIT爆粗的话，对应FAQ中提到应该去抓dmesg看驱动日志中RGA的报错。

**Comment by misakaj** [comment]
感谢大佬回复！！
1.用MPP解码出来的数据就是代绿边的，之前尝试过把解码出来的数据转换为yuv420,但是只对h264起作用，h265还是老样子，而且性能不太行，有没有更好的思路呢？
2.是否和dst_buf的释放有关呢？它的释放时机是什么时候，是需要手动释放还是rga自己会释放呢？

**Comment by misakaj** [comment]
> 感谢大佬回复！！
> 1.用MPP解码出来的数据就是代绿边的，之前尝试过把解码出来的数据转换为yuv420,但是只对h264起作用，h265还是老样子，而且性能不太行，有没有更好的思路呢？
> 2.是否和dst_buf的释放有关呢？它的释放时机是什么时候，是需要手动释放还是rga自己会释放呢？

**Comment by Cerf-Yu** [comment]
内存的管理都是外部根据自己的业务流程去管理的

**Comment by runinnowhere** [comment]
一样的问题，请问解决了吗

**Comment by runinnowhere** [comment]
> 一样的问题，请问解决了吗

我解决了，是rga转换时要字节对其。
<img width="198" alt="微信图片_20240508125324" src="https://github.com/airockchip/librga/assets/150241044/c1284888-b01c-407e-9574-656bdc1b24ac">
