### ISSUE TITLE
err ws Error srcRect

### ISSUE THREAD

**Issue by MrWwei** [airockchip/librga#39]
这里官方给的答案，修改虚宽和实宽是怎么操作的，实宽可以修改吗？
Q3.2.5：日志报错“err ws[100,1280,1280]”、”Error srcRect“ 是什么错误？

A3.2.5：该报错为明显的参数报错，“err ws” 即虚宽（width stride）参数异常，其后“[]”内的参数分别为 [x_offeset, width, width_stride]，这里由于X方向的偏移与实际操作区域的宽的和大于了虚宽，所以librga认为虚宽存在问题而返回的报错。这里只要将虚宽改为1380或将实宽（width）改为1180，即可。

**Comment by Cerf-Yu** [comment]
实宽、虚宽都是你的参数配置，对应到im2d api中，im_rect中的宽即为实宽，意为实际操作的矩形区域的宽。
