### ISSUE TITLE
YUV420SP NV12的数据转成RGB格式，但却提示不支持

### ISSUE THREAD

**Issue by wddnzjwd** [airockchip/librga#40]
我想要把YUV420SP NV12（数据来源：用mpp将jpg解码，解码输出格式为默认得到）的数据转成RGB格式，但却提示不支持：

<img width="556" alt="1689072417527_2F5B5F1B-6D4A-4321-872D-A7012AE668F8" src="https://github.com/airockchip/librga/assets/115400478/7c616c82-f8f6-4582-8150-7b433ca7a1c7">

芯片：RV1126
RGA版本：rga_api version 1.3.2_[0] (1b4d29d build: 2022-05-26 11:11:29 base: )
系统：Debian

相关代码设置部分：
rga_src = wrapbuffer_virtualaddr(yuv_buf, 1920, 1080, RK_FORMAT_YCbCr_420_SP);
rga_src.format = RK_FORMAT_YCbCr_420_SP;

rga_dst = wrapbuffer_virtualaddr(rgb_buf, 1920, 1080, RK_FORMAT_RGB_888);
rga_dst.format = RK_FORMAT_RGB_888;

ret = imcheck(rga_src, rga_dst, src_rect, dst_rect);
ret = imcvtcolor(rga_src, rga_dst, rga_src.format, rga_dst.format);

请问这是真的不支持yuv420SP NV12格式吗？但我看截图上下面写着支持yuv420呀，这是什么原因呢？还是芯片或者rga版本不匹配呢？

**Comment by Cerf-Yu** [comment]
日志明显的打印出来了你配置的格式不是NV12格式而是BPP4格式，建议检查一下头文件是否匹配。
