### ISSUE TITLE
请问在使用rga 调用imcrop时会出现板子整个崩溃情况

### ISSUE THREAD

**Issue by Sacmer** [airockchip/librga#43]
多线程在调用使用imcrop操作时会偶发性出现
RgaBlit(1465) RGA BLIT fail: Device or resource busy
RgaBlit(1466) RGA BLIT fail: Device or resource busy
cropping.... , Fatal error: Failed to call RockChipRga interface,
query log to find the cause of failure.报错 并且当产生这个报错时候 整个板子的网络延迟剧增甚至会断连崩溃

rga驱动版本是RGA multicore Device Driver: v1.2.20
api版本是RGA_api version       : v1.8.1_[4]
板子型号是 rk3588

**Comment by Sacmer** [comment]
@Cerf-Yu 大佬求回复 
使用mpp多路解码 并对解码出来的帧用rga进行imcrop操作时会出现这个报错（偶发性）
每次出现这种情况时候，网络延迟会剧增甚至整个交换机范围内的网络都会断掉，然后整个板子就会崩溃
![微信截图_20230823104348](https://github.com/airockchip/librga/assets/45823520/f2051ac0-55a0-4297-b278-bde9865f8329)

**Comment by Cerf-Yu** [comment]
![image](https://github.com/airockchip/librga/assets/52726484/e864e758-1711-412a-9cca-fc6a1fe60b0e)
