### ISSUE TITLE
使用RGA的时候报错，查阅文档没有发现对应错误

### ISSUE THREAD

**Issue by 7288Fzq** [airockchip/librga#44]
RgaBlit(1483) RGA_BLIT fail: Invalid argument
 RgaBlit(1484) RGA_BLIT fail: Invalid argument
handl-fd-vir-phy-hnd-format[0, 231, (nil), (nil), 0, 0]
rect[0, 0, 1920, 1080, 2304, 1080, 2560, 0]
f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 1]
handl-fd-vir-phy-hnd-format[0, 208, (nil), (nil), 0, 0]
rect[0, 0, 1920, 1080, 2304, 1080, 2560, 0]
f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 1]
This output the user patamaters when rga call blit fail
203607 im2d_rga_impl rga_task_submit(1943): Failed to call RockChipRga interface, please use 'dmesg' command to view driver error log.
203607 im2d_rga_impl rga_dump_channel_info(1418): src_channel:
  rect[x,y,w,h] = [0, 0, 0, 0]
  image[w,h,ws,hs,f] = [1920, 1080, 2304, 1080, nv12]
  buffer[handle,fd,va,pa] = [0, 231, 0, 0]
  color_space = 0x0, global_alpha = 0x0, rd_mode = 0x0

203607 im2d_rga_impl rga_dump_channel_info(1418): dst_channel:
  rect[x,y,w,h] = [0, 0, 0, 0]
  image[w,h,ws,hs,f] = [1920, 1080, 2304, 1080, nv12]
  buffer[handle,fd,va,pa] = [0, 208, 0, 0]
  color_space = 0x0, global_alpha = 0x0, rd_mode = 0x0

203607 im2d_rga_impl rga_dump_opt(1468): opt version[0x0]:

203607 im2d_rga_impl rga_dump_opt(1469): set_core[0x0], priority[0]

203607 im2d_rga_impl rga_task_submit(1952): acquir_fence[-1], release_fence_ptr[0x0], usage[0x80000]

**Comment by Cerf-Yu** [comment]
![image](https://github.com/airockchip/librga/assets/52726484/5423ccb9-2d29-48ae-99cf-cea7cf4aaeeb)

**Comment by evil-ac** [comment]
请问解决了吗

**Comment by 7288Fzq** [comment]
> 请问解决了吗

解决了，RGA一般不会有问题，是自己代码问题。

**Comment by lofyol** [comment]
@7288Fzq 请问如何解决这个问题的

**Comment by boss-dog** [comment]
> > 请问解决了吗
> 
> 解决了，RGA一般不会有问题，是自己代码问题。

请问是怎么解决的？我是在rk3588上运行的yolov8-seg模型，使用官方的yolov8x-seg模型转成rknn之后，用官方的代码推理就没问题，替换为我自己训练的模型，就报上面这个错了
