### ISSUE TITLE
mpp解码后的内存放入rga，报"RGA2 only support under 4G memory!"

### ISSUE THREAD

**Issue by zouzhongy** [airockchip/librga#49]
![Screenshot from 2023-10-30 18-29-34 (copy)](https://github.com/airockchip/librga/assets/40787944/06282694-5b79-4147-90ff-75ada0a73e2f)
这个内存是mpp解码后的内存，某些帧会报这个错误，其他帧调用rga正常。

**Comment by zouzhongy** [comment]
RGA multicore Device Driver: v1.2.25
rga_api version 1.9.1_[5]

**Comment by zouzhongy** [comment]
![Screenshot from 2023-10-31 15-10-08](https://github.com/airockchip/librga/assets/40787944/a95d1fce-a450-4bc5-8207-e09fcce1bde5)
补充提交一个日志，不知道是不是和under 4G memory一个错误。

**Comment by zouzhongy** [comment]
看起来不是一个问题，全部使用rga_allocator_dma32_demo.cpp里面分类内存的方式，没有看到有RGA2 only support under 4G memory!,但是还是会有后面的问题RGA3经常reset。

**Comment by Cerf-Yu** [comment]
你这个问题报错前面是超时，buffer在4G内存空间以外的情况可以看到依旧有匹配到硬件核心，所以和4G问题无关。
timeout可以参考以下解决方案进行排查，自查后以后存在问题建议提一个redmine。
![Uploading image.png…]()

**Comment by Cerf-Yu** [comment]
![image](https://github.com/airockchip/librga/assets/52726484/92f52245-8a19-46af-8ce3-f805ed083ffb)

**Comment by zouzhongy** [comment]
使用under 4G memory，然后调高DDR频率，可以解决。
