### ISSUE TITLE
咨询一下rk 3588 imcvtcolor报错问题。

### ISSUE THREAD

**Issue by CNoob4ever** [airockchip/librga#5]
char* src_buf = mpp_buffer_get_ptr(mpp_src_buf);
    char* dst_buf = mpp_buffer_get_ptr(mpp_dst_buf);
    ALOGV("src_buf: %p,dst_buf: %p.", src_buf, dst_buf);

    int src_fd = mpp_buffer_get_fd(mpp_src_buf);
    int dst_fd = mpp_buffer_get_fd(mpp_dst_buf);
    ALOGV("src_fd: %p,dst_fd: %p.", src_fd, dst_fd);

    if(src_fmt == MPP_FMT_YUV420SP){
        src.format = RK_FORMAT_YCbCr_420_SP;
    }else{
        ALOGE("id:%u, unknown format %s\n", mId, src_fmt);
        return MPP_NOK;
    }
    dst.format = RK_FORMAT_ARGB_8888;

    src = wrapbuffer_virtualaddr(src_buf, src_w, src_h, src.format);
    dst = wrapbuffer_virtualaddr(dst_buf, dst_w, dst_h, dst.format);

    IM_STATUS ret = imcheck(src, dst, src_rect, dst_rect);
    if (IM_STATUS_NOERROR != ret) {
        ALOGE("id:%u, check error! %s\n", mId, imStrError((IM_STATUS)ret));
        return MPP_NOK;
    }

    STATUS = imcvtcolor(src, dst, src.format, dst.format);
    if(STATUS != IM_STATUS_NOERROR && STATUS != IM_STATUS_SUCCESS){
        ALOGE("id:%u, cvtcolor rga_convert faild: (error code: %d) %s\n", mId, STATUS, imStrError(STATUS));
        return MPP_NOK;
    }
mpp日志报错：
![3827CE3D0DF45A6FEE21FD450863DBF3](https://user-images.githubusercontent.com/22703081/176816379-61fc6579-1e74-491f-8736-06fcc0153a1b.jpg)

请问用虚拟地址初始化为什么会报这个错误？

**Comment by Cerf-Yu** [comment]
RK3588上的RGA3硬件不支持ARGB8888格式，而使用RGA2核心的话需要使用4G以内内存空间的内存调用。
