### ISSUE TITLE
请问 librga 可以用来加速 计算psnr/ssim等图像指标吗?

### ISSUE THREAD

**Issue by pengbins** [airockchip/librga#50]
发现用硬解之后, 到CPU计算psnr 会很慢, 比直接读取yuv计算psnr 慢很多
猜测应该是yuv数据 copy到内存比较慢, 如果能直接用librga 计算的话, 是不是就可以避免copy, 速度会快很多?

比如psnr 其实只是两个图像做差, 然后计算差值的平方和, 原理上librga是不是也比较擅长做这个?

**Comment by Cerf-Yu** [comment]
这个RGA硬件是不支持的。
