### ISSUE TITLE
flush RGA cache

### ISSUE THREAD

**Issue by bluesky2319** [airockchip/librga#58]
您好，我们的转码应用程序运行 libgstrockchipmpp，它处理 RGA2，但是当任务被终止并重新运行时，我们面临：

`rga_mm: the following RGA_MMU unsupported Memory larger than 4G!
`
同时，通过监控系统使用情况，我看到内存低于2GB。 我很奇怪为什么我会遇到这个问题。 此外，由于我们不直接处理 RGA，调试它给我们带来了一些挑战。 我认为问题与RGA的缓存有关，任务被杀死后没有刷新。 我想知道是否有任何命令可以在终端上运行来清除RGA的缓存。 如果没有，是否有其他方法可以在不处理 RGA 代码的情况下解决此问题？ 我将不胜感激你的回答。

**Comment by bluesky2319** [comment]
@blackaddwhite 感谢您与我分享的信息。 我在 RK3588 的 4GB/8GB/16GB RAM 和内核版本 5.10 中看到了这个问题。 我在FriendlyARM 的内核版本6.1 中没有看到这个问题，即使是4GB。
FriendlyARM使用RGA驱动版本1.2.27和RGA_api 1.9.3，不知道是什么原因。 是否与内核版本、驱动版本或您提到的其他内容有关？
新内核版本 (6.1) 的问题是 CPU 使用率比 5.10 更高。

**Comment by blackaddwhite** [comment]
> @blackaddwhite 感谢您与我分享的信息。 我在 RK3588 的 4GB/8GB/16GB RAM 和内核版本 5.10 中看到了这个问题。 我在FriendlyARM 的内核版本6.1 中没有看到这个问题。 FriendlyARM使用RGA驱动版本1.2.27和RGA_api 1.9.3，不知道是什么原因。 是否与内核版本、驱动版本或您提到的其他内容有关？ 新内核版本 (6.1) 的问题是 CPU 使用率比 5.10 更高。
> 
> 另外，当我们看到这个错误时，我们是否需要考虑并修复它，或者我们可以忽略这个问题吗？ 我问这个问题是因为我在结果中没有看到任何不利影响（视觉上）。

如果在使用了4GB ddr内存的设备上也出现了此类报错，且在其他内核版本时此类报错消失，那么我猜测大概率是内核版本和驱动版本的问题，而与我上次回复中提到的“rga申请的内存没有正确释放”无关。我也遇到过rga的报错，并且更新内核版本后消失了。如果后续开发中没有使用到rga或mpp等硬件加速器，我想是可以忽略这个问题的，但如果条件允许，还是建议更新，就我自身在这款cpu上的视频应用开发经历而言，老的内核还存在一些其他问题会影响应用正常运行，但通过更新内核后都得到了很好的解决。

**Comment by bluesky2319** [comment]
再次感谢你。 我差不多明白了。 然后，我们将尝试使用不同的驱动程序版本和新的内核版本。 但据我所知，新的内核6.1尚未正式发布。 有没有新的内核版本下载源？我只看到这个来源：https://github.com/JeffyCN/rockchip_mirrors
