### ISSUE TITLE
对于使用wrapbuffer_fd和imcopy进行图像拷贝的疑惑？

### ISSUE THREAD

**Issue by worldhe** [airockchip/librga#7]
rga_buffer_t wrapbuffer_fd(int fd, 
                           int width, 
                           int height,
                           int wstride = width, 
                           int hstride = height,
                           int format);
使用wrapbuffer_fd缓存src图像。
使用warpbuffer_fd缓存dst图像。
我想使用imcopy进行图像拷贝。请问warpbuffer_fd缓存dst图像时，第一个fd参数应该怎样设置，要和warpbuffer_fd缓存src的第一个参数一致吗？

**Comment by Cerf-Yu** [comment]
图像拷贝的话一共是两块buffer，一个是输入图像的dma_fd，一个是输出buffer的dma_fd，dst通道填写拷贝的目标buffer的dma_fd即可。

**Comment by worldhe** [comment]
感谢@Cerf-Yu 提示，谢谢。
