### ISSUE TITLE
可以提供一下librga.so的依赖库吗

### ISSUE THREAD

**Issue by wy9884255** [airockchip/librga#9]
导出编译为库时，提示缺少依赖库

**Comment by wy9884255** [comment]
libgrallocatypes.so

**Comment by wy9884255** [comment]
![3ad5059d59858725d8ac07802b2f8d3](https://user-images.githubusercontent.com/37665832/190849968-d6a9f949-36eb-4747-8aea-efc34e335fd1.png)

**Comment by Cerf-Yu** [comment]
这个看起来是在android环境下编译的，这个依赖都是在android环境内的，可以尝试在android编译后output中查找，如果是要单独使用建议使用ndk编译，librga使用ndk编译时会隔离掉这部分与系统强相关的依赖。
